name: "bloo"

slack:
  bot_name: "slackbot"

classifier:
  categories:
    - office
    - greeting
    - identification

  datasets:
    - data/classifier/office.txt
    - data/classifier/greeting.txt
    - data/classifier/identification.txt

satellite:
  host: 'localhost'
  port: 8000
